builds:
  - main: dummy.go
    goarch: [ amd64, aarch64 ]
    binary: dummy
    hooks:
      post: sh build/cross-release.sh

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
nfpms:
  -
    package_name: "{{ .ProjectName }}"
    vendor: Scott Jackson
    homepage: https://github.com/scottmmjackson/upnotify
    maintainer: Scott Jackson <scottmmjackson@gmail.com>
    description: Notifies when a server is up or down by logging to the console.
    license: BSD 3.0
    formats:
      - deb
      - rpm
      - termux.deb
      - archlinux
# Disable snapcrafts, they don't work
#snapcrafts:
#  -
#    publish:  false
#    summary: Converts pull request tasks from bitbucket to todo txt tasks
#    description: Converts pull request tasks from bitbucket to todo txt tasks
brews:
  -
    tap:
      owner: scottmmjackson
      name: homebrew-sj
      token: '{{ .Env.BREW_GITHUB_TOKEN }}'
      pull_request:
        enabled: true
        base: main
    folder: Formula
    homepage: "https://github.com/scottmmjackson/upnotify"
    description: Notifies when a server is up or down by logging to the console.
    test: |
      system "#{bin}/upnotify -v"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
