name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build-mac-m1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-apple-darwin
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/cache@v3
        with:
          path: target/aarch64-apple-darwin
  build-mac-x86:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-apple-darwin
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/cache@v3
        with:
          path: target/x86_64-apple-darwin
  build-linux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/cache@v3
        with:
          path: aarch64-unknown-linux-gnu
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/cache@v3
        with:
          path: x86_64-unknown-linux-gnu
  build-windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/cache@v3
        with:
          path: x86_64-pc-windows-msvc
  build-windows-aarch64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/cache@v3
        with:
          path: aarch64-pc-windows-msvc
  archive:
    runs-on: ubuntu-latest
    needs:
      - build-mac-m1
      - build-mac-x86
      - build-linux-aarch64
      - build-linux-x86_64
      - build-windows-x86_64
      - build-windows-aarch64
    steps:
      - uses: extractions/setup-just@v1
      - run: just archive-all do-release-package
